Repository csatar/csatar-october, pull requests merged in 2023-04, with the labels that each got.

#310 CS-380 display scout team change history
  csatar-plugins/csatar/classes/HistoryService.php
  csatar-plugins/csatar/controllers/history/config_filter.yaml
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/ContentPage.php
  csatar-plugins/csatar/models/History.php
  csatar-plugins/csatar/models/Scout.php
  csatar-plugins/csatar/plugin.yaml
  csatar-plugins/csatar/updates/builder_table_create_csatar_csatar_history.php
  csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_8.php
  csatar-theme/pages/tag.htm
Labels: codeball:needs-review

#293 CS-492 - Fixed street field in locations table
  Changelog.md
  csatar-plugins/csatar/models/Locations.php
  csatar-plugins/csatar/updates/LocationData.php
Labels: codeball:needs-careful-review

#308 CS-520 Modification_optimization of grid display
  Changelog.md
  csatar-plugins/csatar/assets/recordlist/recordList.css
  csatar-plugins/csatar/assets/recordlist/recordList.js
  csatar-plugins/csatar/components/RecordList.php
  csatar-plugins/csatar/components/accidentlogrecordlist/default.htm
  csatar-plugins/csatar/components/accidentlogrecordlist/listItem.htm
  csatar-plugins/csatar/components/organizationunitfrontend/inactiveMandates.htm
  csatar-plugins/csatar/components/recordlist/filter.htm
  csatar-plugins/csatar/components/recordlist/filters.htm
  csatar-plugins/csatar/components/recordlist/filtersActive.htm
  csatar-plugins/csatar/components/recordlist/tableHeader.htm
  csatar-plugins/csatar/components/recordlist/tableRow.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/TrialSystem.php
  csatar-plugins/knowledgerepository/models/trialsystem/columns.yaml
  csatar-theme/assets/css/csatar-custom-styles.css
  csatar-theme/pages/tudastar/probarendszerek.htm
  csatar-theme/partials/site/layout.htm
Labels: codeball:needs-careful-review

#299 CS-529 games import - 2*
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/knowledgerepository/classes/xlsx/GamesXlsxImport.php
  csatar-plugins/knowledgerepository/controllers/Games.php
  csatar-plugins/knowledgerepository/controllers/games/_import_errors.htm
  csatar-plugins/knowledgerepository/controllers/games/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/games/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/games/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/games/create.htm
  csatar-plugins/knowledgerepository/controllers/games/import.htm
  csatar-plugins/knowledgerepository/controllers/games/preview.htm
  csatar-plugins/knowledgerepository/controllers/games/update.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/updates/SeederData.php
Labels: codeball:needs-careful-review

#306 CS-475 - Added option to delete scout with personal data - 1*
  Changelog.md
  csatar-plugins/csatar/classes/BackendExtensions.php
  csatar-plugins/csatar/controllers/Scouts.php
  csatar-plugins/csatar/controllers/scouts/_list_toolbar.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/Scout.php
Labels: codeball:needs-careful-review

#309 CS-553 Move html to partial from formbuilder trait
  csatar-plugins/forms/components/basicform/partials/pivotSection.htm
  csatar-plugins/forms/components/basicform/partials/pivotTableHeader.htm
  csatar-plugins/forms/components/basicform/partials/pivotTableRow.htm
  csatar-plugins/forms/components/basicform/partials/pivotTableRowCol.htm
  csatar-plugins/forms/components/basicform/partials/pivotTableRowColButtons.htm
  csatar-plugins/forms/components/basicform/partials/relationOptions.htm
  csatar-plugins/forms/components/basicform/partials/validationTags.htm
  csatar-plugins/forms/traits/AjaxControllerSimple.php
Labels: codeball:needs-careful-review

#312 CS-555 - Added Google calendar to Association, District, Team
  Changelog.md
  csatar-plugins/csatar/components/organizationunitfrontend/default.htm
  csatar-plugins/csatar/controllers/seederdata/seeder.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/Association.php
  csatar-plugins/csatar/models/District.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/association/fields.yaml
  csatar-plugins/csatar/models/district/fields.yaml
  csatar-plugins/csatar/models/team/fields.yaml
  csatar-plugins/csatar/updates/SeederData.php
  csatar-plugins/csatar/updates/update_teams_districts_associations_add_google_calendar_id.php
  csatar-plugins/csatar/updates/version.yaml
Labels: codeball:approved

#313 CS-533 - Modified search results to display order
  csatar-plugins/csatar/Plugin.php
  csatar-plugins/csatar/classes/OrganizationSearchProvider.php
Labels: codeball:approved

#318 CS-394 - Added inactive mandates to scout's page
  csatar-plugins/csatar/models/Mandate.php
  csatar-plugins/csatar/models/Scout.php
  csatar-theme/pages/tag.htm
Labels: codeball:approved

#322 CS-500 - Restore deleted scouts on backend
  Changelog.md
  csatar-plugins/csatar/Plugin.php
  csatar-plugins/csatar/controllers/Scouts.php
  csatar-plugins/csatar/controllers/scouts/_list_toolbar.htm
  csatar-plugins/csatar/controllers/scouts/_list_toolbar_trashed.htm
  csatar-plugins/csatar/controllers/scouts/config_list_trashed.yaml
  csatar-plugins/csatar/controllers/scouts/deleted.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/Scout.php
Labels: codeball:approved

#323 CS-559 Created CSMTV
  Changelog.md
  csatar-plugins/csatar/classes/Constants.php
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/csatar/components/organizationunitfrontend/default.htm
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/knowledgerepository/Plugin.php
  csatar-plugins/knowledgerepository/assets/css/workPlan.css
  csatar-plugins/knowledgerepository/controllers/WorkPlans.php
  csatar-plugins/knowledgerepository/controllers/workplans/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/workplans/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/workplans/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/workplans/create.htm
  csatar-plugins/knowledgerepository/controllers/workplans/index.htm
  csatar-plugins/knowledgerepository/controllers/workplans/preview.htm
  csatar-plugins/knowledgerepository/controllers/workplans/update.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/WorkPlan.php
  csatar-plugins/knowledgerepository/models/workplan/columns.yaml
  csatar-plugins/knowledgerepository/models/workplan/fields.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_work_plans.php
  csatar-plugins/knowledgerepository/updates/version.yaml
  csatar-plugins/knowledgerepository/views/pdf/layouts/workplanlayout.htm
  csatar-plugins/knowledgerepository/views/pdf/workplantemplate.htm
  csatar-theme/pages/csapat.htm
  csatar-theme/pages/letoltes.htm
  csatar-theme/pages/tudastar/munkaterv.htm
Labels: codeball:needs-careful-review

#314 CS-516 - Created Song types model
  Changelog.md
  csatar-plugins/knowledgerepository/controllers/SongTypes.php
  csatar-plugins/knowledgerepository/controllers/seederdata/seeder.htm
  csatar-plugins/knowledgerepository/controllers/songtypes/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/songtypes/_reorder_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/songtypes/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/songtypes/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/songtypes/config_reorder.yaml
  csatar-plugins/knowledgerepository/controllers/songtypes/create.htm
  csatar-plugins/knowledgerepository/controllers/songtypes/index.htm
  csatar-plugins/knowledgerepository/controllers/songtypes/preview.htm
  csatar-plugins/knowledgerepository/controllers/songtypes/reorder.htm
  csatar-plugins/knowledgerepository/controllers/songtypes/update.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/SongType.php
  csatar-plugins/knowledgerepository/models/songtype/columns.yaml
  csatar-plugins/knowledgerepository/models/songtype/fields.yaml
  csatar-plugins/knowledgerepository/plugin.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_song_type.php
  csatar-plugins/knowledgerepository/updates/builder_table_update_csatar_knowledgerepository_song_type.php
  csatar-plugins/knowledgerepository/updates/version.yaml
Labels: codeball:needs-careful-review

#315 CS-517 - Created Folk song type model
  Changelog.md
  csatar-plugins/knowledgerepository/controllers/FolkSongTypes.php
  csatar-plugins/knowledgerepository/controllers/folksongtypes/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/folksongtypes/_reorder_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/folksongtypes/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/folksongtypes/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/folksongtypes/config_reorder.yaml
  csatar-plugins/knowledgerepository/controllers/folksongtypes/create.htm
  csatar-plugins/knowledgerepository/controllers/folksongtypes/index.htm
  csatar-plugins/knowledgerepository/controllers/folksongtypes/preview.htm
  csatar-plugins/knowledgerepository/controllers/folksongtypes/reorder.htm
  csatar-plugins/knowledgerepository/controllers/folksongtypes/update.htm
  csatar-plugins/knowledgerepository/controllers/seederdata/seeder.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/FolkSongType.php
  csatar-plugins/knowledgerepository/models/folksongtype/columns.yaml
  csatar-plugins/knowledgerepository/models/folksongtype/fields.yaml
  csatar-plugins/knowledgerepository/plugin.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_folk_song_type.php
  csatar-plugins/knowledgerepository/updates/version.yaml
Labels: codeball:needs-careful-review

#324 CS-563 - Added Trial System Trial Type to patrol
  Changelog.md
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/patrol/fields.yaml
  csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_patrols_3.php
  csatar-plugins/csatar/updates/version.yaml
  csatar-plugins/knowledgerepository/models/WorkPlan.php
Labels: codeball:approved

#316 CS-518 - Created region model
  Changelog.md
  csatar-plugins/knowledgerepository/controllers/Regions.php
  csatar-plugins/knowledgerepository/controllers/regions/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/regions/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/regions/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/regions/create.htm
  csatar-plugins/knowledgerepository/controllers/regions/index.htm
  csatar-plugins/knowledgerepository/controllers/regions/preview.htm
  csatar-plugins/knowledgerepository/controllers/regions/update.htm
  csatar-plugins/knowledgerepository/controllers/seederdata/seeder.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/Region.php
  csatar-plugins/knowledgerepository/models/region/columns.yaml
  csatar-plugins/knowledgerepository/models/region/fields.yaml
  csatar-plugins/knowledgerepository/plugin.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_region.php
  csatar-plugins/knowledgerepository/updates/builder_table_update_csatar_knowledgerepository_region.php
  csatar-plugins/knowledgerepository/updates/version.yaml
Labels: codeball:needs-careful-review

#317 CS-519 - Created Folk song rhythm model
  Changelog.md
  csatar-plugins/knowledgerepository/controllers/FolkSongRhythms.php
  csatar-plugins/knowledgerepository/controllers/folksongrhythms/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/folksongrhythms/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/folksongrhythms/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/folksongrhythms/create.htm
  csatar-plugins/knowledgerepository/controllers/folksongrhythms/index.htm
  csatar-plugins/knowledgerepository/controllers/folksongrhythms/preview.htm
  csatar-plugins/knowledgerepository/controllers/folksongrhythms/update.htm
  csatar-plugins/knowledgerepository/controllers/seederdata/seeder.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/FolkSongRhythm.php
  csatar-plugins/knowledgerepository/models/folksongrhythm/columns.yaml
  csatar-plugins/knowledgerepository/models/folksongrhythm/fields.yaml
  csatar-plugins/knowledgerepository/plugin.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_folk_song_rhythm.php
  csatar-plugins/knowledgerepository/updates/version.yaml
Labels: codeball:needs-careful-review

#326 CS-551 - Created Waiting For Approval accordions on Games, Methodolog…
  Changelog.md
  csatar-plugins/csatar/assets/recordlist/recordList.js
  csatar-plugins/csatar/components/RecordList.php
  csatar-plugins/csatar/components/recordlist/default.htm
  csatar-plugins/csatar/components/recordlist/filter.htm
  csatar-plugins/csatar/components/recordlist/filters.htm
  csatar-plugins/csatar/components/recordlist/filtersActive.htm
  csatar-plugins/knowledgerepository/components/GameForm.php
  csatar-plugins/knowledgerepository/components/MethodologyForm.php
  csatar-plugins/knowledgerepository/components/SongForm.php
  csatar-plugins/knowledgerepository/components/gameform/additionalData.htm
  csatar-plugins/knowledgerepository/components/methodologyform/additionalData.htm
  csatar-plugins/knowledgerepository/components/songform/additionalData.htm
  csatar-plugins/knowledgerepository/models/Game.php
  csatar-plugins/knowledgerepository/models/Methodology.php
  csatar-plugins/knowledgerepository/models/Song.php
  csatar-plugins/knowledgerepository/models/game/columnsWaitingForApproval.yaml
  csatar-plugins/knowledgerepository/models/methodology/columnsWaitingForApproval.yaml
  csatar-plugins/knowledgerepository/models/song/columns.yaml
  csatar-plugins/knowledgerepository/models/song/columnsWaitingForApproval.yaml
  csatar-theme/pages/tudastar/dal.htm
  csatar-theme/pages/tudastar/dalok.htm
  csatar-theme/pages/tudastar/jatek.htm
  csatar-theme/pages/tudastar/jatekok.htm
  csatar-theme/pages/tudastar/modszertan.htm
  csatar-theme/pages/tudastar/modszertanok.htm
Labels: codeball:approved

#327 CS-530 - Added xlsx import for Songs.
  Changelog.md
  csatar-plugins/knowledgerepository/classes/xlsx/GamesXlsxImport.php
  csatar-plugins/knowledgerepository/classes/xlsx/SongsXlsxImport.php
  csatar-plugins/knowledgerepository/classes/xlsx/TrialSystemsXlsxImport.php
  csatar-plugins/knowledgerepository/controllers/Games.php
  csatar-plugins/knowledgerepository/controllers/Songs.php
  csatar-plugins/knowledgerepository/controllers/TrialSystems.php
  csatar-plugins/knowledgerepository/controllers/songs/_import_errors.htm
  csatar-plugins/knowledgerepository/controllers/songs/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/songs/create.htm
  csatar-plugins/knowledgerepository/controllers/songs/import.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
Labels: codeball:needs-careful-review
