Repository csatar/csatar-october, pull requests merged in 2023-02, with the labels that each got.

#238 CS-461 - Created membership card requests backend list
  Changelog.md
  csatar-plugins/csatar/classes/CsvCreator.php
  csatar-plugins/csatar/components/AccidentLogRecordList.php
  csatar-plugins/csatar/components/TeamReports.php
  csatar-plugins/csatar/controllers/MembershipCardRequests.php
  csatar-plugins/csatar/controllers/membershipcardrequests/_list_toolbar.htm
  csatar-plugins/csatar/controllers/membershipcardrequests/config_list.yaml
  csatar-plugins/csatar/controllers/membershipcardrequests/index.htm
  csatar-plugins/csatar/controllers/membershipcards/_list_toolbar.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/MembershipCardRequest.php
  csatar-plugins/csatar/models/membershipcardrequest/columns.yaml
  csatar-theme/pages/balesetek-csv-letoltes.htm
Labels: codeball:needs-review

#235 CS-466 Created tables for "Knowledge repository" models
  Changelog.md
  csatar-plugins/knowledgerepository/Plugin.php
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/plugin.yaml
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_accident_risk_levels.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_age_group_game.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_age_group_methodology.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_development_goal_game.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_development_goals.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_duration.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_game_type.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_headcount.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_location.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_tool.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_types.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_games.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_headcount_methodology.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_headcounts.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_location_methodology.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_locations.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_methodologies.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_methodology_material_type.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_methodology_tool.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_methodology_types.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_timeframes.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_tools.php
  csatar-plugins/knowledgerepository/updates/version.yaml
Labels: codeball:needs-review

#234 CC-327 Create dynamic fields
  Changelog.md
  csatar-plugins/csatar/controllers/DynamicFields.php
  csatar-plugins/csatar/controllers/dynamicfields/_list_toolbar.htm
  csatar-plugins/csatar/controllers/dynamicfields/config_form.yaml
  csatar-plugins/csatar/controllers/dynamicfields/config_list.yaml
  csatar-plugins/csatar/controllers/dynamicfields/create.htm
  csatar-plugins/csatar/controllers/dynamicfields/index.htm
  csatar-plugins/csatar/controllers/dynamicfields/preview.htm
  csatar-plugins/csatar/controllers/dynamicfields/update.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/DynamicFields.php
  csatar-plugins/csatar/models/TeamReport.php
  csatar-plugins/csatar/models/dynamicfields/columns.yaml
  csatar-plugins/csatar/models/dynamicfields/fields.yaml
  csatar-plugins/csatar/models/teamreport/fieldsForBackend.yaml
  csatar-plugins/csatar/plugin.yaml
  csatar-plugins/csatar/updates/builder_table_create_csatar_csatar_dynamic_fields.php
  csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_team_reports.php
  csatar-plugins/csatar/updates/version.yaml
  csatar-plugins/forms/traits/AjaxControllerSimple.php
Labels: codeball:needs-careful-review

#244 CS-436 Added option to hide mandate types on frontend
  Changelog.md
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/Mandate.php
  csatar-plugins/csatar/models/mandatetype/fields.yaml
  csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_mandate_types.php
  csatar-plugins/csatar/updates/version.yaml
  csatar-plugins/forms/traits/AjaxControllerSimple.php
  setup/dev/init.sh
Labels: codeball:needs-review

#243 CS-462 - Added warning to team report
  Changelog.md
  csatar-plugins/csatar/components/TeamReport.php
  csatar-plugins/csatar/components/teamreport/additionalData.htm
  csatar-plugins/csatar/components/teamreport/default.htm
  csatar-plugins/csatar/models/TeamReport.php
Labels: codeball:needs-review

#248 Create Knowledge Repository and Knowledge Repository Parameters menus…
  Changelog.md
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/plugin.yaml
Labels: codeball:needs-review

#250 CS-455 Sort the teams in the menu on the frontend
  Changelog.md
  csatar-plugins/csatar/components/structure/menuItems.htm
  csatar-plugins/csatar/models/District.php
Labels: codeball:needs-review

#245 CS-460 - Added frontend scout csv import-export
  Changelog.md
  csatar-plugins/csatar/classes/enums/Gender.php
  csatar-plugins/csatar/classes/enums/InjurySeverity.php
  csatar-plugins/csatar/classes/enums/Status.php
  csatar-plugins/csatar/classes/mappers/LegalRelationshipMapper.php
  csatar-plugins/csatar/classes/mappers/ReligionMapper.php
  csatar-plugins/csatar/components/AccidentLogRecordList.php
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/csatar/components/organizationunitfrontend/csvImportLog.htm
  csatar-plugins/csatar/components/organizationunitfrontend/csvUploadForm.htm
  csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/AccidentLogRecord.php
  csatar-theme/assets/css/csatar-custom-styles.css
  csatar-theme/pages/csv-letoltes.htm
Labels: codeball:needs-careful-review

#249 CS-363 - Fixed success/error message issue on back list bulk delete
  Changelog.md
  csatar-plugins/csatar/classes/BackendExtensions.php
  csatar-plugins/csatar/controllers/MandateTypes.php
  csatar-plugins/csatar/controllers/Scouts.php
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/MandateType.php
  csatar-plugins/csatar/models/Scout.php
Labels: codeball:needs-review

#252 CS-386 create accident risk level
  Changelog.md
  csatar-plugins/csatar/plugin.yaml
  csatar-plugins/knowledgerepository/controllers/AccidentRiskLevel.php
  csatar-plugins/knowledgerepository/controllers/GameDevelopmentGoals.php
  csatar-plugins/knowledgerepository/controllers/SeederData.php
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/_reorder_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/config_reorder.yaml
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/create.htm
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/index.htm
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/preview.htm
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/reorder.htm
  csatar-plugins/knowledgerepository/controllers/accidentrisklevel/update.htm
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/_reorder_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/config_reorder.yaml
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/create.htm
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/index.htm
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/preview.htm
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/reorder.htm
  csatar-plugins/knowledgerepository/controllers/gamedevelopmentgoals/update.htm
  csatar-plugins/knowledgerepository/controllers/seederdata/seeder.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/AccidentRiskLevel.php
  csatar-plugins/knowledgerepository/models/GameDevelopmentGoal.php
  csatar-plugins/knowledgerepository/models/accidentrisklevel/columns.yaml
  csatar-plugins/knowledgerepository/models/accidentrisklevel/fields.yaml
  csatar-plugins/knowledgerepository/models/gamedevelopmentgoal/columns.yaml
  csatar-plugins/knowledgerepository/models/gamedevelopmentgoal/fields.yaml
  csatar-plugins/knowledgerepository/plugin.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_accident_risk_levels.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_development_goals.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_types.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_headcounts.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_locations.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_methodology_types.php
Labels: codeball:needs-careful-review

#253 CS-375 - Created Tool model, controller, backend list and form
  Changelog.md
  csatar-plugins/knowledgerepository/controllers/GameDevelopmentGoals.php
  csatar-plugins/knowledgerepository/controllers/Tools.php
  csatar-plugins/knowledgerepository/controllers/seederdata/seeder.htm
  csatar-plugins/knowledgerepository/controllers/tools/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/tools/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/tools/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/tools/create.htm
  csatar-plugins/knowledgerepository/controllers/tools/index.htm
  csatar-plugins/knowledgerepository/controllers/tools/preview.htm
  csatar-plugins/knowledgerepository/controllers/tools/update.htm
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/Tool.php
  csatar-plugins/knowledgerepository/models/tool/columns.yaml
  csatar-plugins/knowledgerepository/models/tool/fields.yaml
  csatar-plugins/knowledgerepository/plugin.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_games.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_methodologies.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_tools.php
Labels: codeball:needs-careful-review

#239 CS-311 - Created sort order method for the galleries
  csatar-plugins/csatar/Plugin.php
  csatar-plugins/csatar/assets/touch-dnd.js
  csatar-plugins/csatar/components/CsatarGallery.php
  csatar-plugins/csatar/components/csatargallery/default.htm
  csatar-plugins/csatar/components/csatargallery/galleryImages.htm
  csatar-plugins/csatar/components/csatargallery/sortOrder.htm
  csatar-plugins/csatar/updates/migration_1077.php
  csatar-plugins/csatar/updates/version.yaml
  csatar-theme/assets/vendor/bootstrap-5.1.3/css/bootstrap.css
Labels: codeball:needs-careful-review

#255 CS-397 - Changed accordion on the team,patrol and troop pages
  Changelog.md
  csatar-plugins/csatar/components/Structure.php
  csatar-plugins/csatar/components/organizationunitfrontend/patrolForm.htm
  csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
  csatar-plugins/csatar/components/organizationunitfrontend/troopForm.htm
  csatar-plugins/csatar/components/structure/accordionbody.htm
  csatar-plugins/csatar/components/structure/buttonList.htm
  csatar-plugins/csatar/components/structure/default.htm
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/Troop.php
Labels: codeball:needs-careful-review

#258 CS-460 - Cherry pick csv import-export from develop
  Changelog.md
  csatar-plugins/csatar/classes/CsvCreator.php
  csatar-plugins/csatar/classes/enums/Gender.php
  csatar-plugins/csatar/classes/enums/InjurySeverity.php
  csatar-plugins/csatar/classes/enums/Status.php
  csatar-plugins/csatar/classes/mappers/LegalRelationshipMapper.php
  csatar-plugins/csatar/classes/mappers/ReligionMapper.php
  csatar-plugins/csatar/components/AccidentLogRecordList.php
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/csatar/components/organizationunitfrontend/csvImportLog.htm
  csatar-plugins/csatar/components/organizationunitfrontend/csvUploadForm.htm
  csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/AccidentLogRecord.php
  csatar-plugins/csatar/models/Mandate.php
  csatar-plugins/csatar/models/Scout.php
  csatar-theme/assets/css/csatar-custom-styles.css
  csatar-theme/pages/csv-letoltes.htm
Labels: codeball:needs-review

#259 CS-397 - Cherry pick accordion changes from the develop
  Changelog.md
  csatar-plugins/csatar/components/Structure.php
  csatar-plugins/csatar/components/organizationunitfrontend/patrolForm.htm
  csatar-plugins/csatar/components/organizationunitfrontend/teamForm.htm
  csatar-plugins/csatar/components/organizationunitfrontend/troopForm.htm
  csatar-plugins/csatar/components/structure/accordionbody.htm
  csatar-plugins/csatar/components/structure/buttonList.htm
  csatar-plugins/csatar/components/structure/default.htm
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/Troop.php
Labels: codeball:needs-careful-review

#261 CS-478 Optimize structure queries
  csatar-plugins/csatar/classes/StructureTree.php
  csatar-plugins/csatar/components/Structure.php
  csatar-plugins/csatar/components/structure/accordionItems.htm
  csatar-plugins/csatar/components/structure/accordionbody.htm
  csatar-plugins/csatar/components/structure/default.htm
  csatar-plugins/csatar/components/structure/menuItems.htm
  csatar-plugins/csatar/controllers/PermissionsMatrix.php
  csatar-plugins/csatar/models/Association.php
  csatar-plugins/csatar/models/District.php
  csatar-plugins/csatar/models/Mandate.php
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/Scout.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/Troop.php
Labels: codeball:needs-careful-review

#262 CS-461 - Created membership card requests backend list
  Changelog.md
  csatar-plugins/csatar/components/AccidentLogRecordList.php
  csatar-plugins/csatar/components/TeamReports.php
  csatar-plugins/csatar/controllers/MembershipCardRequests.php
  csatar-plugins/csatar/controllers/membershipcardrequests/_list_toolbar.htm
  csatar-plugins/csatar/controllers/membershipcardrequests/config_list.yaml
  csatar-plugins/csatar/controllers/membershipcardrequests/index.htm
  csatar-plugins/csatar/controllers/membershipcards/_list_toolbar.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/MembershipCardRequest.php
  csatar-plugins/csatar/models/membershipcardrequest/columns.yaml
Labels: codeball:needs-review

#264 CS-498 optimized inactive mandates accordion
  Changelog.md
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/csatar/components/organizationunitfrontend/inactiveMandates.htm
  csatar-plugins/csatar/models/Association.php
  csatar-plugins/csatar/models/District.php
  csatar-plugins/csatar/models/Mandate.php
  csatar-plugins/csatar/models/OrganizationBase.php
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/Troop.php
Labels: codeball:needs-review

#256 CS-454: Remove the Team column from the Mandates tables
  Changelog.md
  csatar-plugins/csatar/models/mandate/columns.yaml
Labels: codeball:needs-careful-review

#257 CS-452: Mandate Types must have different names
  Changelog.md
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/MandateType.php
Labels: codeball:needs-careful-review

#273 CS-411 Fixed the header on the team page
  Changelog.md
  csatar-theme/assets/css/csatar-custom-styles.css
Labels: codeball:approved

#276 CS-387 Create Game model
  .editorconfig
  Changelog.md
  csatar-plugins/csatar/Plugin.php
  csatar-plugins/csatar/components/Partials.php
  csatar-plugins/csatar/controllers/PermissionsMatrix.php
  csatar-plugins/csatar/controllers/SeederData.php
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/PermissionBasedAccess.php
  csatar-plugins/forms/traits/AjaxControllerSimple.php
  csatar-plugins/knowledgerepository/Plugin.php
  csatar-plugins/knowledgerepository/components/GameForm.php
  csatar-plugins/knowledgerepository/components/gameform/additionalData.htm
  csatar-plugins/knowledgerepository/components/gameform/default.htm
  csatar-plugins/knowledgerepository/components/gameform/form.htm
  csatar-plugins/knowledgerepository/controllers/GameDevelopmentGoals.php
  csatar-plugins/knowledgerepository/controllers/Games.php
  csatar-plugins/knowledgerepository/controllers/games/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/games/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/games/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/games/create.htm
  csatar-plugins/knowledgerepository/controllers/games/index.htm
  csatar-plugins/knowledgerepository/controllers/games/preview.htm
  csatar-plugins/knowledgerepository/controllers/games/update.htm
  csatar-plugins/knowledgerepository/controllers/seederdata/seeder.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/Game.php
  csatar-plugins/knowledgerepository/models/Headcount.php
  csatar-plugins/knowledgerepository/models/game/columns.yaml
  csatar-plugins/knowledgerepository/models/game/fields.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_games.php
  csatar-plugins/knowledgerepository/updates/builder_table_update_csatar_knowledgerepository_games.php
  csatar-plugins/knowledgerepository/updates/version.yaml
  csatar-theme/pages/tudastar/jatek.htm
  csatar-theme/pages/tudastar/jatekok.htm
  csatar-theme/partials/site/navigation.htm
Labels: codeball:needs-careful-review

#278 CS-489 Added citizenship column to scout
  Changelog.md
  csatar-plugins/csatar/Plugin.php
  csatar-plugins/csatar/classes/mappers/CountryMapper.php
  csatar-plugins/csatar/classes/validators/CnpValidator.php
  csatar-plugins/csatar/components/Breadcrumb.php
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/csatar/components/organizationunitfrontend/csvUploadForm.htm
  csatar-plugins/csatar/controllers/seederdata/seeder.htm
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/MandateType.php
  csatar-plugins/csatar/models/Scout.php
  csatar-plugins/csatar/models/scout/fields.yaml
  csatar-plugins/csatar/updates/SeederData.php
  csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_6.php
  csatar-plugins/csatar/updates/version.yaml
  csatar-theme/pages/uptdate-exisiting-scouts-citizenship.htm
Labels: codeball:needs-review

#277 CS-493 Added active members count to Association, District, Team, Troop, Patrol models
  Changelog.md
  csatar-plugins/csatar/classes/StructureTree.php
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/Association.php
  csatar-plugins/csatar/models/District.php
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/Troop.php
  csatar-plugins/csatar/models/association/fields.yaml
  csatar-plugins/csatar/models/district/fields.yaml
  csatar-plugins/csatar/models/patrol/fields.yaml
  csatar-plugins/csatar/models/team/fields.yaml
  csatar-plugins/csatar/models/troop/fields.yaml
  csatar-plugins/forms/traits/AjaxControllerSimple.php
Labels: codeball:needs-careful-review

#260 CS-481: Simplify the scout validation for inactive scouts
  csatar-plugins/csatar/models/Scout.php
Labels: codeball:needs-review
