Repository csatar/csatar-october, pull requests merged in 2023-03, with the labels that each got.

#283 CS-502 - Fixed incorrect cache update process
  csatar-plugins/csatar/models/Association.php
  csatar-plugins/csatar/models/District.php
  csatar-plugins/csatar/models/OrganizationBase.php
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/Scout.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/Troop.php
Labels: codeball:needs-review

#282 CS-480 - Fixed leadership qualification not showing in downloaded TeamReport pdf
  csatar-plugins/csatar/components/TeamReport.php
  csatar-plugins/csatar/components/teamreport/fullForm.htm
  csatar-plugins/csatar/updates/SeederData.php
  csatar-plugins/csatar/views/pdf/layouts/teamreportlayout.htm
Labels: codeball:approved

#284 CS-327 Changes in dynamic fields
  csatar-plugins/csatar/components/TeamReport.php
  csatar-plugins/csatar/models/dynamicfields/columns.yaml
  csatar-plugins/csatar/models/dynamicfields/fields.yaml
  csatar-plugins/csatar/views/pdf/layouts/teamreportlayout.htm
  csatar-plugins/forms/traits/AjaxControllerSimple.php
Labels: codeball:needs-careful-review

#280 CS-387 Added TagList (multiselect) widget to form builder
  Changelog.md
  csatar-plugins/csatar/Plugin.php
  csatar-plugins/forms/assets/css/storm-select2.css
  csatar-plugins/forms/assets/css/storm.css
  csatar-plugins/forms/components/BasicForm.php
  csatar-plugins/forms/traits/AjaxControllerSimple.php
  csatar-plugins/forms/widgets/TagList.php
  csatar-plugins/forms/widgets/frontendfileupload/partials/_frontendfileupload.htm
  csatar-plugins/forms/widgets/taglist/HasRelationStore.php
  csatar-plugins/forms/widgets/taglist/HasStringStore.php
  csatar-plugins/forms/widgets/taglist/partials/_taglist.htm
  csatar-plugins/knowledgerepository/controllers/GameTypes.php
  csatar-plugins/knowledgerepository/controllers/Games.php
  csatar-plugins/knowledgerepository/models/game/fields.yaml
  csatar-theme/assets/css/csatar-custom-styles.css
Labels: codeball:needs-careful-review

#281 CS-411 Fixed image overflowing the screen
  Changelog.md
  csatar-plugins/csatar/components/csatargallery/edit.htm
  csatar-plugins/csatar/components/csatargallery/galleryCover.htm
  csatar-plugins/csatar/components/csatargallery/sortOrder.htm
  csatar-plugins/forms/components/basicform/partials/mainCard.htm
  csatar-plugins/forms/components/basicform/partials/sheetCard.htm
  csatar-theme/assets/css/csatar-custom-styles.css
  csatar-theme/partials/DesignSystem/cards.htm
  csatar-theme/partials/site/header.htm
  csatar-theme/partials/site/navigation.htm
Labels: codeball:needs-careful-review

#285 CS-452 Change error message by Mandate Types
  csatar-plugins/csatar/lang/en/lang.php
  csatar-plugins/csatar/lang/hu/lang.php
  csatar-plugins/csatar/models/MandateType.php
Labels: codeball:approved

#286 CS-474 - Delete Scout name if inactivated more than 5 years ago
  csatar-plugins/csatar/Plugin.php
  csatar-plugins/csatar/classes/StructureTree.php
  csatar-plugins/csatar/components/CheckScoutStatus.php
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/csatar/components/TeamReport.php
  csatar-plugins/csatar/controllers/MembershipCardRequests.php
  csatar-plugins/csatar/models/Mandate.php
  csatar-plugins/csatar/models/MembershipCard.php
  csatar-plugins/csatar/models/Patrol.php
  csatar-plugins/csatar/models/Scout.php
  csatar-plugins/csatar/models/ScoutImport.php
  csatar-plugins/csatar/models/Team.php
  csatar-plugins/csatar/models/TeamReport.php
  csatar-plugins/csatar/models/Troop.php
  csatar-plugins/csatar/models/scout/columns.yaml
  csatar-plugins/csatar/updates/builder_table_update_csatar_csatar_scouts_7.php
  csatar-plugins/csatar/updates/version.yaml
Labels: codeball:approved

#287 CS-497 - Number of Patrols in Age Group field required
  Changelog.md
  csatar-plugins/csatar/models/TeamReport.php
  csatar-plugins/csatar/models/TeamReportAgeGroupPivot.php
  csatar-plugins/csatar/models/agegroup/fieldsPivot.yaml
Labels: codeball:approved

#279 CS-506 - Added Xdebug setup commands
  docker-compose.yml
  setup/dev/Readme.md
  setup/dev/init-xdebug.cmd
  setup/dev/init-xdebug.sh
Labels: codeball:needs-careful-review

#274 CS-377 - Created Methodology model and backend form
  Changelog.md
  csatar-plugins/csatar/models/AgeGroup.php
  csatar-plugins/csatar/models/Scout.php
  csatar-plugins/knowledgerepository/Plugin.php
  csatar-plugins/knowledgerepository/components/MethodologyForm.php
  csatar-plugins/knowledgerepository/components/methodologyform/additionalData.htm
  csatar-plugins/knowledgerepository/components/methodologyform/default.htm
  csatar-plugins/knowledgerepository/components/methodologyform/form.htm
  csatar-plugins/knowledgerepository/controllers/Methodologies.php
  csatar-plugins/knowledgerepository/controllers/methodologies/_list_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/methodologies/_reorder_toolbar.htm
  csatar-plugins/knowledgerepository/controllers/methodologies/config_form.yaml
  csatar-plugins/knowledgerepository/controllers/methodologies/config_list.yaml
  csatar-plugins/knowledgerepository/controllers/methodologies/config_reorder.yaml
  csatar-plugins/knowledgerepository/controllers/methodologies/create.htm
  csatar-plugins/knowledgerepository/controllers/methodologies/index.htm
  csatar-plugins/knowledgerepository/controllers/methodologies/preview.htm
  csatar-plugins/knowledgerepository/controllers/methodologies/reorder.htm
  csatar-plugins/knowledgerepository/controllers/methodologies/update.htm
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/AgeGroupMethodologyPivot.php
  csatar-plugins/knowledgerepository/models/Duration.php
  csatar-plugins/knowledgerepository/models/Headcount.php
  csatar-plugins/knowledgerepository/models/HeadcountMethodologyPivot.php
  csatar-plugins/knowledgerepository/models/Location.php
  csatar-plugins/knowledgerepository/models/LocationMethodologyPivot.php
  csatar-plugins/knowledgerepository/models/Methodology.php
  csatar-plugins/knowledgerepository/models/MethodologyToolPivot.php
  csatar-plugins/knowledgerepository/models/MethodologyType.php
  csatar-plugins/knowledgerepository/models/Tool.php
  csatar-plugins/knowledgerepository/models/methodology/columns.yaml
  csatar-plugins/knowledgerepository/models/methodology/fields.yaml
  csatar-plugins/knowledgerepository/updates/SeederData.php
  csatar-plugins/knowledgerepository/updates/builder_table_update_csatar_knowledgerepository_methodologies.php
  csatar-plugins/knowledgerepository/updates/version.yaml
  csatar-theme/pages/tudastar/jatekok.htm
  csatar-theme/pages/tudastar/modszertan.htm
  csatar-theme/pages/tudastar/modszertanok.htm
  csatar-theme/partials/site/navigation.htm
Labels: codeball:needs-careful-review

#289 CS-377 - Fixed methodology create/edit form
  csatar-plugins/forms/components/BasicForm.php
  csatar-plugins/knowledgerepository/models/Methodology.php
  csatar-plugins/knowledgerepository/models/methodology/approverscout.htm
  csatar-plugins/knowledgerepository/models/methodology/fields.yaml
  csatar-plugins/knowledgerepository/models/methodology/uploaderscout.htm
  csatar-theme/pages/tudastar/modszertan.htm
Labels: codeball:approved

#297 CS-331 Added PWA support - 1*
  Changelog.md
  Readme.md
  csatar-theme/manifest.json
  csatar-theme/partials/site/meta.htm
Labels: codeball:approved

#298 CS-491 - Added scout xlsx import/export to teams page - 2*
  Changelog.md
  csatar-plugins/csatar/classes/xlsx/ScoutXlsxExport.php
  csatar-plugins/csatar/classes/xlsx/ScoutXlsxImport.php
  csatar-plugins/csatar/components/AccidentLogRecordList.php
  csatar-plugins/csatar/components/OrganizationUnitFrontend.php
  csatar-plugins/csatar/components/organizationunitfrontend/csvXlsxImportLog.htm
  csatar-plugins/csatar/components/organizationunitfrontend/csvXlsxUploadForm.htm
  csatar-plugins/csatar/components/structure/buttonList.htm
  csatar-theme/pages/csv-letoltes.htm
  csatar-theme/pages/letoltes.htm
Labels: codeball:approved, codeball:needs-careful-review

#295 CS-514 - Added trial system to Methodologies - 1*
  csatar-plugins/knowledgerepository/lang/en/lang.php
  csatar-plugins/knowledgerepository/lang/hu/lang.php
  csatar-plugins/knowledgerepository/models/Methodology.php
  csatar-plugins/knowledgerepository/models/game/fields.yaml
  csatar-plugins/knowledgerepository/models/methodology/fields.yaml
  csatar-plugins/knowledgerepository/models/trialsystem/columns.yaml
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_knowledgerepository_game_trial_system.php
  csatar-plugins/knowledgerepository/updates/builder_table_create_csatar_methodology_trial_system.php
  csatar-plugins/knowledgerepository/updates/version.yaml
Labels: codeball:approved
